# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavorrate',
            options={'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
    ]
